### ISSUE TITLE
cordova-plugin-idfa + Ionic

### ISSUE THREAD

**Issue by wo-github** [chemerisuk/cordova-plugin-idfa#1]
Hello,
could you post a example how to integrate this plugin in a Ionic App?

**Comment by chemerisuk** [comment]
Sorry, I have no experience with ionic.

**Comment by chemerisuk** [comment]
@wo-github you could try to ask @adamduren

**Comment by adamduren** [comment]
In Ionic you can access it globally in a component, service, etc, as you would with any other global variable. However Angular recommends using their dependency injection system to make it easier to test by providing an easy way to mock dependencies.

Ionic has `ionic-native` which provides utilities to make it easier to build providers for Angular which wrap cordova apis but one is currently not available for this plugin. An example where I've done this in the past can be seen in [this PR](https://github.com/ionic-team/ionic-native/pull/2518/files).

The simplest way without depending on globals in your components and services is to go the Angular only route. Here's some code which should closely

```typescript
import { Platform } from 'ionic-angular';
import { Injectable } from '@angular/core';

@Injectable()
class IDFAService {

  constructor(private platform: Platform) {}

  public getInfo(): Promise<string> {
    return this.platform
      .ready()
      .then(() => cordova.plugins.idfa.getInfo())
  }

}

@NgModule({
  // Other NgModule fields ...
  providers: [
    // Other providers ...
    IDFAService,
  ],
})
export class AppModule {
}
```
