### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by ghost** [chemerisuk/cordova-plugin-idfa#10]
Can you please provide a small example of HTML/JS code for testing?

On my test devices nothing is displayed in the console.

**Comment by BendingBender** [comment]
[This small example](https://github.com/chemerisuk/cordova-plugin-idfa#example) doesn't help?

**Comment by nskoro** [comment]
alternative way to use it: https://rubberchickin.com/implement-app-tracking-transparency-for-ionic-angular-and-cordova-ios-app/
