### ISSUE TITLE
Using this plugin only for AppTrackingTransparency

### ISSUE THREAD

**Issue by Nargonath** [chemerisuk/cordova-plugin-idfa#11]
I'm using Ionic@4 and since Apple made it mandatory to use the `AppTrackingTransparency` for iOS >= 14.5 I'm looking for a plugin that handles it. I use Cordova and not Capacitor so your plugin seems to be the only solution available from what I found. The thing is I do not use any ads within the app. The only reason I need to abide by the `AppTrackingTransparency` module is because I use `firebase-analytics` and for user's contact info so I don't need any IDFA. Do you foresee any problem using your package for such a use case or are there none?

Thank you for your work on this project and your help. 🙏

**Comment by BradCB** [comment]
I am wondering the same thing. I use firebase-analytics, firebase-crashlytics and firebase-cloud messaging. I only log info in crashlytics and don't use any ads.  I disable analytics and anonymize crashlytics data if permission is not granted using this plugin. 

Also, is there any way to listen, in cordova, for when the AppTrackingTransparency has been toggled on the device?

**Comment by chemerisuk** [comment]
Afaik firebase analytics uses idfa to collect demographic, age, gender data etc. So even when you don’t have ads and don’t store idfa on backend those values stored at google servers. That’s why you still have to use AppTrackingTransparency.

**Comment by Nargonath** [comment]
Alright makes sense @chemerisuk . Thank you for the explanation. I guess there are no problem using your plugin in that case. I'll close this now.
