### ISSUE TITLE
Permission request on IOS 15.3.1 does not work

### ISSUE THREAD

**Issue by SPLAYER-HD** [chemerisuk/cordova-plugin-idfa#21]
Hi,
The permission request pop up does not appear in IOS 15.3.1. Could you help me please

**Comment by JamalAPI** [comment]
I have the same issue. I was working prior iOS updates.

**Comment by SPLAYER-HD** [comment]
> I have the same issue. I was working prior iOS updates.

Hi mate, the real problem is that IOS is not loading in a queue the notifications, so the permission request is being sending but as there are other permission request first, it shows them first so it does not show the last one.

I fixed doing a cycle to ask for the permission every 20 seconds until the user answer accept or deny.

**Comment by SidiBecker** [comment]
I created a fork with a implementation that I saw on Apple forum, and worked good. I created the pull request https://github.com/chemerisuk/cordova-plugin-idfa/pull/22. There are guidelines to use the fork.

**Comment by JamalAPI** [comment]
@SidiBecker, thanks for the fork. It worked perfectly and app was approved 👍
