### ISSUE TITLE
requestPermission not showing dialog in release version

### ISSUE THREAD

**Issue by aktivdigital-frontend** [chemerisuk/cordova-plugin-idfa#29]
Hi! If I run app in development version, request permission dialog shows. But after I archive and I upload to store, and I download it from TestFlight, not shows it. What is the problem? Thank you!

**Comment by SmallBlueE** [comment]
Finally,  did you fix this issue?

**Comment by SmallBlueE** [comment]
> Hi! If I run app in development version, request permission dialog shows. But after I archive and I upload to store, and I download it from TestFlight, not shows it. What is the problem? Thank you!

Finally, did you fix this issue?
