### ISSUE TITLE
Plugin throws error on release build

### ISSUE THREAD

**Issue by amitchoubey** [chemerisuk/cordova-plugin-idfa#3]
We have integrated this plugin for a cordova based hybrid application and plugin working fine for the debug build but same when we are preparing build to release on play store that build is not working.

Please let me me know if any thing has to be added in progaurd.txt file for android.

**Comment by craig-at-rsg** [comment]
It looks like this plugin uses https://github.com/chemerisuk/cordova-support-android-plugin, and the README for that says to include the lines below, which worked for me.

```
-keepclassmembers class ** {
  @by.chemerisuk.cordova.support.CordovaMethod *;
}
-keep public enum by.chemerisuk.cordova.support.ReflectiveCordovaPlugin$** {
    **[] $VALUES;
    public *;
}
```
