### ISSUE TITLE
Conflict plugins cordova-plugin-idfa and phonegap-plugin-push

### ISSUE THREAD

**Issue by nevstas** [chemerisuk/cordova-plugin-idfa#6]
I got error when add two plugins to my project (cordova-plugin-idfa and phonegap-plugin-push)

cordova create MyApp
cordova platform add android
cordova plugin add cordova-plugin-idfa

Add:
\<preference name="AndroidXEnabled" value="true" />
To config.xml in section:
\<platform name="android">

Copy google-services.json to "platforms\android\app\google-services.json"

cordova plugin add phonegap-plugin-push

cordova build android

And I got error:

> Task :app:compileDebugJavaWithJavac FAILED
C:\projects_cordova\MyApp\platforms\android\app\src\main\java\com\adobe\phonegap\push\BackgroundActionButtonHandler.java:9: error: cannot find symbol
import android.support.v4.app.RemoteInput;
                             ^
  symbol:   class RemoteInput
  location: package android.support.v4.app
C:\projects_cordova\MyApp\platforms\android\app\src\main\java\com\adobe\phonegap\push\FCMService.java:26: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
C:\projects_cordova\MyApp\platforms\android\app\src\main\java\com\adobe\phonegap\push\FCMService.java:27: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
C:\projects_cordova\MyApp\platforms\android\app\src\main\java\com\adobe\phonegap\push\FCMService.java:28: error: cannot find symbol
import android.support.v4.app.RemoteInput;
                             ^
  symbol:   class RemoteInput
  location: package android.support.v4.app
C:\projects_cordova\MyApp\platforms\android\app\src\main\java\com\adobe\phonegap\push\FCMService.java:528: error: package NotificationCompat does not exist
  private void createActions(Bundle extras, NotificationCompat.Builder mBuilder, Resources resources...

Versions:

c:\projects_cordova\MyApp>cordova platform
Installed platforms:
android 9.0.0

c:\projects_cordova\MyApp>cordova plugin
cordova-plugin-idfa 1.2.0 "cordova-plugin-idfa"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.3.0 "PushPlugin"

**Comment by chemerisuk** [comment]
You are trying to mix androidX and support libraries on Android.
