### ISSUE TITLE
requesting permission to track the user iOS14?

### ISSUE THREAD

**Issue by matrixreal** [chemerisuk/cordova-plugin-idfa#7]
Hello,
Is there a way to request permission to track the user in iOS14 with thi plugin?
Thanks

**Comment by chemerisuk** [comment]
Decided not to add such API until the dialog will be a requirement https://github.com/chemerisuk/cordova-plugin-idfa/pull/5

**Comment by matrixreal** [comment]
How you do that ? can you tell what's the call?
Thanks

**Comment by BendingBender** [comment]
https://github.com/chemerisuk/cordova-plugin-idfa/pull/5#issuecomment-705659100
